"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import Image from "next/image";

export default function SweetToothZoneSection() {
  const [meals, setMeals] = useState([]);
  const [loading, setLoading] = useState(true);

  const dessertCaptions = [
    "A treat you won’t forget",
    "Sweetness overloaded",
    "Pure dessert magic",
    "Melt-in-your-mouth goodness",
    "Spoonfuls of joy",
    "Too good to share",
    "Sugar, spice, and everything nice",
    "For your inner sweet tooth",
    "An exquisite confection.",
    "The epitome of sweet indulgence.",
    "Crafted with passion and sweetness.",
    "A delicate dance of flavors.",
    "The art of sweet creation.",
    "Indulge in the extraordinary.",
    "A taste of pure luxury.",
    "Sophisticated sweetness.",
    "Elegance in every bite.",
    "The grand finale to any meal.",
    "Experience sweet artistry.",
    "A moment of refined sweetness.",
    "Sweetness elevated.",
    "The perfect touch of elegance.",
    "A truly special sweet treat.",
    "Savor the sweet sophistication.",
    "Where sweetness meets artistry.",
    "Indulge in a sweet masterpiece.",
    "A touch of sweet opulence.",
    "The ultimate in sweet refinement.",
    "Celebrate with exquisite sweetness.",
    "Treat yourself to something special.",
    "Life's sweeter with this.",
    "Happiness served daily.",
    "A little slice of heaven.",
    "Sweet moments.",
    "Making life sweeter, one dessert at a time.",
    "The sweet escape you deserve.",
    "Indulge. Enjoy. Repeat.",
    "Sweet memories are made of this.",
    "Find your sweet spot.",
    "The perfect ending starts here.",
    "A daily dose of delicious.",
    "Sweetness is the key to happiness.",
    "Baking the world a better place, one dessert at a time.",
    "Whisk me away to dessert land.",
    "Have your cake and eat it too!",
    "Stirring up some sweet happiness.",
    "Proof that magic exists.",
    "Good things come in sweet packages.",
    "Creating sweet smiles.",
    "A little sweet therapy.",
    "The answer is always dessert.",
    "Keep calm and eat dessert.",
    "Dessert solves everything.",
    "In a world full of options, choose sweet.",
    "Sweetening the soul.",
    "A taste of pure delight.",
    "Happiness is just a dessert away.",
    "Making every day a little sweeter.",
    "The simple joy of dessert.",
    "Sweetness to brighten your day.",
    "A perfect sweet ending.",
    "Indulge your senses.",
    "Experience the sweet life.",
    "Savor every sweet moment.",
    "The ultimate comfort food.",
    "A little bit of sweet indulgence.",
    "Treat your taste buds.",
    "The sweet reward.",
    "Pure dessert pleasure.",
    "A taste of happiness.",
    "Sweetness and joy in every bite.",
    "The perfect sweet escape.",
    "Indulge in pure deliciousness.",
    "Sweet cravings, meet your match.",
    "A delightful sweet experience.",
    "The art of sweet satisfaction.",
    "Experience true sweet bliss.",
    "A little bit of sweet paradise.",
    "The taste of pure happiness.",
    "Sweetness that makes you smile.",
    "Indulge in the sweet life.",
    "A moment of sweet perfection.",
    "The ultimate sweet temptation.",
    "Sweetness to brighten your day.",
    "A perfect sweet ending.",
    "Indulge your senses.",
    "Experience the sweet life.",
    "Savor every sweet moment.",
    "The ultimate comfort food.",
    "A little bit of sweet indulgence.",
    "Treat your taste buds.",
    "The sweet reward.",
    "Pure dessert pleasure.",
    "A taste of happiness.",
    "Sweetness and joy in every bite.",
    "The perfect sweet escape.",
    "Indulge in pure deliciousness.",
    "Sweet cravings, meet your match.",
    "A delightful sweet experience.",
    "The art of sweet satisfaction.",
    "Experience true sweet bliss.",
    "A little bit of sweet paradise.",
    "The taste of pure happiness.",
    "Sweetness that makes you smile.",
    "Indulge in the sweet life.",
    "A moment of sweet perfection.",
    "The ultimate sweet temptation.",
    "Sweetness to brighten your day.",
    "A perfect sweet ending.",
    "Indulge your senses.",
    "Experience the sweet life.",
    "Savor every sweet moment.",
    "The ultimate comfort food.",
    "A little bit of sweet indulgence.",
    "Treat your taste buds.",
    "The sweet reward.",
    "Pure dessert pleasure.",
    "A taste of happiness.",
    "Sweetness and joy in every bite.",
    "The perfect sweet escape.",
    "Indulge in pure deliciousness.",
    "Sweet cravings, meet your match.",
    "A delightful sweet experience.",
    "The art of sweet satisfaction.",
    "Experience true sweet bliss.",
    "A little bit of sweet paradise.",
    "The taste of pure happiness.",
    "Sweetness that makes you smile.",
    "Indulge in the sweet life.",
    "A moment of sweet perfection.",
    "The ultimate sweet temptation.",
    "Sweetness to brighten your day.",
    "A perfect sweet ending.",
    "Indulge your senses.",
    "Experience the sweet life.",
    "Savor every sweet moment.",
    "The ultimate comfort food.",
    "A little bit of sweet indulgence.",
    "Treat your taste buds.",
    "The sweet reward.",
    "Pure dessert pleasure.",
    "A taste of happiness.",
    "Sweetness and joy in every bite.",
    "The perfect sweet escape.",
    "Indulge in pure deliciousness.",
    "Sweet cravings, meet your match.",
    "A delightful sweet experience.",
    "The art of sweet satisfaction.",
    "Experience true sweet bliss.",
    "A little bit of sweet paradise.",
    "The taste of pure happiness.",
    "Sweetness that makes you smile.",
    "Indulge in the sweet life.",
    "A moment of sweet perfection.",
    "The ultimate sweet temptation.",
    "Sweetness to brighten your day.",
    "A perfect sweet ending.",
    "Indulge your senses.",
    "Experience the sweet life.",
    "Savor every sweet moment.",
    "The ultimate comfort food.",
    "A little bit of sweet indulgence.",
    "Treat your taste buds.",
    "The sweet reward.",
    "Pure dessert pleasure.",
    "A taste of happiness.",
    "Sweetness and joy in every bite.",
    "The perfect sweet escape.",
    "Indulge in pure deliciousness.",
    "Sweet cravings, meet your match.",
    "A delightful sweet experience.",
    "The art of sweet satisfaction.",
    "Experience true sweet bliss.",
    "A little bit of sweet paradise.",
    "The taste of pure happiness.",
    "Sweetness that makes you smile.",
    "Indulge in the sweet life.",
    "A moment of sweet perfection.",
    "The ultimate sweet temptation.",
    "Sweetness to brighten your day.",
    "A perfect sweet ending.",
    "Indulge your senses.",
    "Experience the sweet life.",
    "Savor every sweet moment.",
    "The ultimate comfort food.",
    "A little bit of sweet indulgence.",
    "Treat your taste buds.",
    "The sweet reward.",
    "Pure dessert pleasure.",
    "A taste of happiness.",
    "Sweetness and joy in every bite.",
    "The perfect sweet escape.",
    "Indulge in pure deliciousness.",
    "Sweet cravings, meet your match.",
    "A delightful sweet experience.",
    "The art of sweet satisfaction.",
    "Experience true sweet bliss.",
    "A little bit of sweet paradise.",
    "The taste of pure happiness.",
    "Sweetness that makes you smile.",
    "Indulge in the sweet life.",
    "A moment of sweet perfection.",
    "The ultimate sweet temptation.",
    "Sweetness to brighten your day.",
    "A perfect sweet ending.",
    "Indulge your senses.",
    "Experience the sweet life.",
    "Savor every sweet moment.",
    "The ultimate comfort food.",
    "A little bit of sweet indulgence.",
    "Treat your taste buds.",
    "The sweet reward.",
    "Pure dessert pleasure.",
    "A taste of happiness.",
    "Sweetness and joy in every bite.",
    "The perfect sweet escape.",
    "Indulge in pure deliciousness.",
    "Sweet cravings, meet your match.",
    "A delightful sweet experience.",
    "The art of sweet satisfaction.",
    "Experience true sweet bliss.",
    "A little bit of sweet paradise.",
    "The taste of pure happiness.",
    "Sweetness that makes you smile.",
    "Indulge in the sweet life.",
    "A moment of sweet perfection.",
    "The ultimate sweet temptation.",
    "Sweetness to brighten your day.",
    "A perfect sweet ending.",
    "Indulge your senses.",
    "Experience the sweet life.",
    "Savor every sweet moment.",
    "The ultimate comfort food.",
    "A little bit of sweet indulgence.",
    "Treat your taste buds.",
    "The sweet reward.",
    "Pure dessert pleasure.",
    "A taste of happiness.",
    "Sweetness and joy in every bite.",
    "The perfect sweet escape.",
    "Indulge in pure deliciousness.",
    "Sweet cravings, meet your match.",
    "A delightful sweet experience.",
    "The art of sweet satisfaction.",
    "Experience true sweet bliss.",
    "A little bit of sweet paradise.",
    "The taste of pure happiness.",
    "Sweetness that makes you smile.",
    "Indulge in the sweet life.",
    "A moment of sweet perfection.",
    "The ultimate sweet temptation.",
    "Sweetness to brighten your day.",
    "A perfect sweet ending.",
    "Indulge your senses.",
    "Experience the sweet life.",
    "Savor every sweet moment.",
    "The ultimate comfort food.",
    "A little bit of sweet indulgence.",
    "Treat your taste buds.",
    "The sweet reward.",
    "Pure dessert pleasure.",
    "A taste of happiness.",
    "Sweetness and joy in every bite.",
    "The perfect sweet escape.",
    "Indulge in pure deliciousness.",
    "Sweet cravings, meet your match.",
    "A delightful sweet experience.",
    "The art of sweet satisfaction.",
    "Experience true sweet bliss.",
    "A little bit of sweet paradise.",
    "The taste of pure happiness.",
    "Sweetness that makes you smile.",
    "Indulge in the sweet life.",
    "A moment of sweet perfection.",
    "The ultimate sweet temptation.",
    "Sweetness to brighten your day.",
    "A perfect sweet ending.",
    "Indulge your senses.",
    "Experience the sweet life.",
    "Savor every sweet moment.",
    "The ultimate comfort food.",
    "A little bit of sweet indulgence.",
    "Treat your taste buds.",
    "The sweet reward.",
    "Pure dessert pleasure.",
    "A taste of happiness.",
    "Sweetness and joy in every bite.",
    "The perfect sweet escape.",
    "Indulge in pure deliciousness.",
    "Sweet cravings, meet your match.",
    "A delightful sweet experience.",
    "The art of sweet satisfaction.",
    "Experience true sweet bliss.",
    "A little bit of sweet paradise.",
    "The taste of pure happiness.",
    "Sweetness that makes you smile.",
    "Indulge in the sweet life.",
    "A moment of sweet perfection.",
    "The ultimate sweet temptation.",
    "Sweetness to brighten your day.",
    "A perfect sweet ending.",
    "Indulge your senses.",
    "Experience the sweet life.",
    "Savor every sweet moment.",
    "The ultimate comfort food.",
    "A little bit of sweet indulgence.",
    "Treat your taste buds.",
    "The sweet reward.",
    "Pure dessert pleasure.",
    "A taste of happiness.",
    "Sweetness and joy in every bite.",
    "The perfect sweet escape.",
    "Indulge in pure deliciousness.",
    "Sweet cravings, meet your match.",
    "A delightful sweet experience.",
    "The art of sweet satisfaction.",
    "Experience true sweet bliss.",
    "A little bit of sweet paradise.",
    "The taste of pure happiness.",
    "Sweetness that makes you smile.",
    "Indulge in the sweet life.",
    "A moment of sweet perfection.",
    "The ultimate sweet temptation.",
    "Sweetness to brighten your day.",
    "A perfect sweet ending.",
    "Indulge your senses.",
    "Experience the sweet life.",
    "Savor every sweet moment.",
    "The ultimate comfort food.",
    "A little bit of sweet indulgence.",
    "Treat your taste buds.",
    "The sweet reward.",
    "Pure dessert pleasure.",
    "A taste of happiness.",
    "Sweetness and joy in every bite.",
    "The perfect sweet escape.",
    "Indulge in pure deliciousness.",
    "Sweet cravings, meet your match.",
    "A delightful sweet experience.",
    "The art of sweet satisfaction.",
    "Experience true sweet bliss.",
    "A little bit of sweet paradise.",
    "The taste of pure happiness.",
    "Sweetness that makes you smile.",
    "Indulge in the sweet life.",
    "A moment of sweet perfection.",
    "The ultimate sweet temptation.",
    "Sweetness to brighten your day.",
    "A perfect sweet ending.",
    "Indulge your senses.",
    "Experience the sweet life.",
    "Savor every sweet moment.",
    "The ultimate comfort food.",
    "A little bit of sweet indulgence.",
    "Treat your taste buds.",
    "The sweet reward.",
    "Pure dessert pleasure.",
    "A taste of happiness.",
    "Sweetness and joy in every bite.",
    "The perfect sweet escape.",
    "Indulge in pure deliciousness.",
    "Sweet cravings, meet your match.",
    "A delightful sweet experience.",
    "The art of sweet satisfaction.",
    "Experience true sweet bliss.",
    "A little bit of sweet paradise.",
    "The taste of pure happiness.",
    "Sweetness that makes you smile.",
    "Indulge in the sweet life.",
    "A moment of sweet perfection.",
    "The ultimate sweet temptation.",
    "Sweetness to brighten your day.",
    "A perfect sweet ending.",
    "Indulge your senses.",
    "Experience the sweet life.",
    "Savor every sweet moment.",
    "The ultimate comfort food.",
    "A little bit of sweet indulgence.",
    "Treat your taste buds.",
    "The sweet reward.",
    "Pure dessert pleasure.",
    "A taste of happiness.",
    "Sweetness and joy in every bite.",
    "The perfect sweet escape.",
    "Indulge in pure deliciousness.",
    "Sweet cravings, meet your match.",
    "A delightful sweet experience.",
    "The art of sweet satisfaction.",
    "Experience true sweet bliss.",
    "A little bit of sweet paradise.",
    "The taste of pure happiness.",
    "Sweetness that makes you smile.",
    "Indulge in the sweet life.",
    "A moment of sweet perfection.",
    "The ultimate sweet temptation.",
    "Sweetness to brighten your day.",
    "A perfect sweet ending.",
    "Indulge your senses.",
    "Experience the sweet life.",
    "Savor every sweet moment.",
    "The ultimate comfort food.",
    "A little bit of sweet indulgence.",
    "Treat your taste buds.",
    "The sweet reward.",
    "Pure dessert pleasure.",
    "A taste of happiness.",
    "Sweetness and joy in every bite.",
    "The perfect sweet escape.",
    "Indulge in pure deliciousness.",
    "Sweet cravings, meet your match.",
    "A delightful sweet experience.",
    "The art of sweet satisfaction.",
    "Experience true sweet bliss.",
    "A little bit of sweet paradise.",
    "The taste of pure happiness.",
    "Sweetness that makes you smile.",
    "Indulge in the sweet life.",
    "A moment of sweet perfection.",
    "The ultimate sweet temptation.",
    "Sweetness to brighten your day.",
    "A perfect sweet ending.",
    "Indulge your senses.",
    "Experience the sweet life.",
    "Savor every sweet moment.",
    "The ultimate comfort food.",
    "A little bit of sweet indulgence.",
    "Treat your taste buds.",
    "The sweet reward.",
    "Pure dessert pleasure.",
    "A taste of happiness.",
    "Sweetness and joy in every bite.",
    "The perfect sweet escape.",
    "Indulge in pure deliciousness.",
    "Sweet cravings, meet your match.",
    "A delightful sweet experience.",
    "The art of sweet satisfaction.",
    "Experience true sweet bliss.",
    "A little bit of sweet paradise.",
    "The taste of pure happiness.",
    "Sweetness that makes you smile.",
    "Indulge in the sweet life.",
    "A moment of sweet perfection.",
    "The ultimate sweet temptation.",
    "Sweetness to brighten your day.",
    "A perfect sweet ending.",
    "Indulge your senses.",
    "Experience the sweet life.",
    "Savor every sweet moment.",
    "The ultimate comfort food.",
    "A little bit of sweet indulgence.",
    "Treat your taste buds.",
    "The sweet reward.",
    "Pure dessert pleasure."
  ];

  useEffect(() => {
    const fetchDessertMeals = async () => {
      try {
        const res = await fetch("https://www.themealdb.com/api/json/v1/1/filter.php?c=Dessert");
        const data = await res.json();
        setMeals(data.meals.slice(0, 8)); // Show only first 8 desserts
      } catch (err) {
        console.error("Failed to fetch dessert meals:", err);
      } finally {
        setLoading(false);
      }
    };

    fetchDessertMeals();
  }, []);

  return (
    <section
      className="px-6 py-16 text-center relative"
      style={{
        background: "linear-gradient(135deg, #ffe0ec, #fff6f9)",
      }}
    >
      {/* Floating Emojis */}
      <div className="absolute top-6 left-6 text-3xl animate-bounce">🍩</div>
      <div className="absolute top-8 right-10 text-3xl animate-pulse">🍫</div>
      <div className="absolute top-3 left-1/2 transform -translate-x-1/2 text-3xl animate-spin">🧁</div>

      <h2 className="text-4xl font-bold mb-2 text-[#D00000]">Sweet Tooth Zone 🍰</h2>
      <p className="text-lg text-gray-700 mb-10">
        Need a treat? Explore desserts that melt hearts (and mouths).
      </p>

      {loading ? (
        <div className="flex justify-center items-center py-12">
          <div className="w-12 h-12 border-4 border-[#D00000] border-t-transparent rounded-full animate-spin"></div>
        </div>
      ) : (
        <div className="flex justify-center flex-wrap gap-6">
          {meals.map((meal) => (
            <div
              key={meal.idMeal}
              className="w-[220px] bg-white rounded-xl p-4 transition transform hover:-translate-y-1 hover:shadow-lg"
              style={{ boxShadow: "2px 2px 3px rgba(0, 0, 0, 0.1)" }}
            >
              <Image
                src={meal.strMealThumb}
                alt={meal.strMeal}
                width={300}
                height={200}
                className="rounded-md object-cover"
              />
              <h4 className="mt-3 text-lg font-semibold">{meal.strMeal}</h4>
              <p className="text-sm text-gray-600 mb-3">
                {dessertCaptions[Math.floor(Math.random() * dessertCaptions.length)]}
              </p>

              <Link href={`../../recipes/${meal.idMeal}`} style={{ cursor: 'pointer' }}>
                <button className="w-full bg-[#D00000] text-white px-4 py-2 rounded-md hover:opacity-90 transition"style={{ cursor: 'pointer' }}>
                  Whip It Up
                </button>
              </Link>
            </div>
          ))}
        </div>
      )}
    </section>
  );
}
