import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { metadata } from '../metadata'; // import metadata
import { ClerkProvider } from '@clerk/nextjs';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
              <head>
          <title>{metadata.title}</title>
          <meta name="description" content={metadata.description} />
        </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} style={{ backgroundColor: "#E5E5E5", color: "#333" }}>
        {children}
      </body>
    </html>
    </ClerkProvider>
  );
}